apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Finbook-api
  description: A very simple API definition for Backstage demo
spec:
  type: openapi
  lifecycle: experimental
  owner: developers
  definition: |
    openapi: 3.0.0
    info:
      title: Simple API
      version: 1.0.0
    paths:
      /hello:
        get:
          summary: Says hello
          responses:
            '200':
              description: Successful response
